### ISSUE TITLE
Keypress does not seem to work

### ISSUE THREAD

**Issue by aragon999** [PixlOne/logiops#181] opened 2020-12-14 12:01 UTC
I am using logid with sway in Archlinux, but I seem to be not able to get the Keypress to work, either in the gestures or for other buttons, for example the following config the commented part works (toggles smartshift) while the `Keypress` action type does not work:
```
        {
            cid: 0xc4;
            action =
            {
                type: "Keypress";
                keys: ["KEY_A"];
            }
#            action =
#            {
#                type: "ToggleSmartshift";
#            };
        }
```

Is there anything I can help with debugging? Or can you point me to some code where I can start debugging?

**Comment by kris7t** [comment] 2020-12-14 12:03
Probably a duplicate of https://github.com/PixlOne/logiops/issues/166

**Comment by aragon999** [comment] 2020-12-14 12:06
Yes that seems to be the case. Sorry I did not see this issue before. I will close this issue as a duplicate.

**Closed** 2020-12-14 12:06 UTC
